In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv("/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/Class6/train.csv")
t=pd.read_csv("/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/Class8/tips.csv")

In [15]:
df
t

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
t.groupby('day')['tip'].mean().round(2)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [13]:
print(t.groupby('day')['tip'].mean().round(2).max(),"%")

3.26 %

In [18]:
t['tip_pcent']=t['tip']/t['total_bill']*100
t

     total_bill   tip     sex smoker   day    time  size  tip_pcent
0         16.99  1.01  Female     No   Sun  Dinner     2   5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3  16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3  16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2  13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4  14.680765
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2   7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2   8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2   9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2  15.974441

[244 rows x 8 columns]

In [19]:
t.groupby('day')['tip_pcent'].mean().round(2)

day
Fri     16.99
Sat     15.32
Sun     16.69
Thur    16.13
Name: tip_pcent, dtype: float64

In [20]:
t['size'].max()

6

In [24]:
t['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [25]:
t.groupby('size')['tip'].mean().round(3)

size
1    1.438
2    2.582
3    3.393
4    4.135
5    4.028
6    5.225
Name: tip, dtype: float64

In [26]:
t.groupby('smoker').value_counts()

smoker  total_bill  tip    sex     day   time    size  tip_pcent
No      7.25        1.00   Female  Sat   Dinner  1     13.793103    1
        7.51        2.00   Male    Thur  Lunch   2     26.631158    1
        7.56        1.44   Male    Thur  Lunch   2     19.047619    1
        8.35        1.50   Female  Thur  Lunch   2     17.964072    1
        8.51        1.25   Female  Thur  Lunch   2     14.688602    1
                                                                   ..
Yes     40.55       3.00   Male    Sun   Dinner  2     7.398274     1
        43.11       5.00   Female  Thur  Lunch   4     11.598237    1
        44.30       2.50   Female  Sat   Dinner  3     5.643341     1
        45.35       3.50   Male    Sun   Dinner  3     7.717751     1
        50.81       10.00  Male    Sat   Dinner  3     19.681165    1
Name: count, Length: 243, dtype: int64

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [33]:
df.groupby('Pclass')["Survived"].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [2]:
x=np.linspace(10,50)

In [3]:
print(x)

[10.         10.81632653 11.63265306 12.44897959 13.26530612 14.08163265
 14.89795918 15.71428571 16.53061224 17.34693878 18.16326531 18.97959184
 19.79591837 20.6122449  21.42857143 22.24489796 23.06122449 23.87755102
 24.69387755 25.51020408 26.32653061 27.14285714 27.95918367 28.7755102
 29.59183673 30.40816327 31.2244898  32.04081633 32.85714286 33.67346939
 34.48979592 35.30612245 36.12244898 36.93877551 37.75510204 38.57142857
 39.3877551  40.20408163 41.02040816 41.83673469 42.65306122 43.46938776
 44.28571429 45.10204082 45.91836735 46.73469388 47.55102041 48.36734694
 49.18367347 50.        ]

TypeError: unsupported operand type(s) for /: 'int' and 'list'

In [5]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]